# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-19 23:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Solar', '0002_inventario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='Socio',
        ),
        migrations.DeleteModel(
            name='Inventario',
        ),
    ]
