# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-20 01:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Solar', '0005_compra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='Producto',
        ),
        migrations.DeleteModel(
            name='compra',
        ),
    ]
