# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-21 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solar', '0008_auto_20181120_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='Ubicacion',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
