# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-22 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solar', '0009_inventario_ubicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='Codigo',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Codigo'),
        ),
    ]
