# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-28 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solar', '0017_auto_20181128_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='Numero_de_Telefono',
            field=models.CharField(max_length=50, verbose_name='492-000-00-00'),
        ),
    ]
