# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-28 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solar', '0023_ventas_estatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='estatus',
            field=models.CharField(max_length=50, verbose_name=set(['Realizado', 'Pendiente'])),
        ),
    ]
