# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-29 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solar', '0027_auto_20181128_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='Producto_a_Comprar',
            field=models.CharField(default='Boilersolar 10', max_length=50, null=True, verbose_name='Producto a Comprar'),
        ),
        migrations.AddField(
            model_name='ventas',
            name='estatus',
            field=models.CharField(default='Pendiente', max_length=50, null=True, verbose_name='Status'),
        ),
    ]
