# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-19 22:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Solar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Producto', models.CharField(max_length=200)),
                ('Descripcion', models.TextField(max_length=500)),
                ('Precio_Compra', models.DecimalField(decimal_places=1, max_digits=10, null=True)),
                ('Precio_Venta', models.DecimalField(decimal_places=1, max_digits=10, null=True)),
                ('Fecha_de_Compra', models.DateTimeField(default=django.utils.timezone.now)),
                ('Socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
