# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-19 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solar', '0003_auto_20181119_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='inventario',
            fields=[
                ('Codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Producto', models.CharField(max_length=50)),
                ('Cantidad', models.IntegerField()),
                ('fecha_de_compra', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
