# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-20 23:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Solar', '0007_ventas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventas',
            name='venta',
        ),
        migrations.DeleteModel(
            name='Ventas',
        ),
    ]
