# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-22 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solar', '0010_auto_20181122_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='Cantidad',
            field=models.IntegerField(verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='Producto',
            field=models.CharField(max_length=50, verbose_name='Producto'),
        ),
    ]
