# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-23 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solar', '0011_auto_20181122_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('idVenta', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='CodigoVenta')),
                ('Producto', models.CharField(max_length=50, verbose_name='Producto')),
                ('Cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('Precio', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Precio')),
                ('fecha_de_Venta', models.DateField(null=True, verbose_name='FechaVenta')),
                ('Ubicacion_de_Venta', models.CharField(max_length=50, null=True, verbose_name='Ubicacion')),
            ],
        ),
        migrations.AlterField(
            model_name='inventario',
            name='Ubicacion',
            field=models.CharField(max_length=50, null=True, verbose_name='Ubicacion'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='fecha_de_compra',
            field=models.DateField(null=True, verbose_name='Fecha'),
        ),
    ]
