# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-26 16:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Solar', '0012_auto_20181123_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compras',
            name='Precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='compras',
            name='Producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Solar.inventario'),
        ),
    ]
