# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-26 16:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Solar', '0013_auto_20181126_1022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compras',
            old_name='Producto',
            new_name='Venta',
        ),
    ]
