# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-28 18:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Solar', '0015_auto_20181126_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('Apellidos', models.CharField(max_length=50, verbose_name='Apellido')),
                ('Correo', models.EmailField(max_length=254, verbose_name='Correo')),
                ('Cantidad', models.IntegerField(verbose_name='Precio')),
                ('Fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('Producto_a_Comprar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Solar.inventario')),
            ],
        ),
    ]
