# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-28 22:50
from __future__ import unicode_literals

import Solar.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solar', '0020_remove_ventas_producto_a_comprar'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='Producto',
            field=models.CharField(default=Solar.models.inventario, max_length=50, verbose_name='Producto'),
        ),
    ]
