# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-28 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solar', '0022_auto_20181128_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='estatus',
            field=models.CharField(default='Pendiente', max_length=50, verbose_name='Status'),
        ),
    ]
