# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-29 00:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Solar', '0026_auto_20181128_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventas',
            name='Producto',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='estatus',
        ),
    ]
