# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-29 01:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Solar', '0028_auto_20181128_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventas',
            name='Producto_a_Comprar',
        ),
    ]
